name: Build and deploy Python app to Azure Web App - tcdzApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up virtual environment
        run: |
          cd tcdzApi
          python -m venv .my_virt_env
          . .my_virt_env/bin/activate
          which python

      - name: Install dependencies
        run: |
          cd tcdzApi
          . .my_virt_env/bin/activate
          pip install -r requirements.txt

      - name: Show deployed app size (before zip)
        run: du -sh tcdzApi

      - name: Zip artifact for deployment
        run: |
          cd tcdzApi
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_219256825306445DA4FC8BAD81EDEDE6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A0904C738792493386D47C3FA526FD99 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BFEB2D3C0F0549B2856D52A75743B319 }}

      # - name: Clean up existing files in wwwroot
      #   run: |
      #     az webapp ssh --name tcdzApi --resource-group tcdz-rest
      #     cd /home/site/wwwroot
      #     rm -rf *

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tcdzApi'
          slot-name: 'Production'
